name: api_alunos
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.13.0-282.4.beta

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
